package report

import (
	"html/template"
	"os"
	"path/filepath"
	"sort"
	"time"

	"github.com/FlinnZee/breachhound/internal/core"
)

// htmlData is the view model handed to the HTML template.
type htmlData struct {
	Host        *core.HostModel
	GeneratedAt string
	RiskScore   int
	Verdict     core.Verdict
	VerdictCSS  string
	Tactics     []tacticGroup
	Skipped     []string
}

type tacticGroup struct {
	Tactic   string
	Findings []core.Finding
}

var htmlTmpl = template.Must(template.New("report").Funcs(template.FuncMap{
	"sev": func(s core.Severity) string { return s.String() },
	"conf": func(c core.Confidence) string { return c.String() },
}).Parse(htmlSource))

// WriteHTML writes a styled report.html into dir and returns its path.
func WriteHTML(dir string, host *core.HostModel, r core.Result) (string, error) {
	groups := GroupByTactic(r.Findings)
	var tactics []tacticGroup
	for t, fs := range groups {
		tactics = append(tactics, tacticGroup{Tactic: t, Findings: fs})
	}
	sort.Slice(tactics, func(i, j int) bool { return tactics[i].Tactic < tactics[j].Tactic })

	data := htmlData{
		Host:        host,
		GeneratedAt: time.Now().Format(time.RFC1123),
		RiskScore:   r.RiskScore,
		Verdict:     r.Verdict,
		VerdictCSS:  verdictClass(r.Verdict),
		Tactics:     tactics,
		Skipped:     r.Skipped,
	}

	path := filepath.Join(dir, "report.html")
	f, err := os.Create(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	if err := htmlTmpl.Execute(f, data); err != nil {
		return "", err
	}
	return path, nil
}

func verdictClass(v core.Verdict) string {
	switch v {
	case core.VerdictCompromised:
		return "bad"
	case core.VerdictReview:
		return "warn"
	default:
		return "good"
	}
}

const htmlSource = `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>BreachHound Report — {{.Host.Hostname}}</title>
<style>
 body{font-family:system-ui,Segoe UI,Arial,sans-serif;margin:0;background:#0e1116;color:#e6edf3}
 header{padding:24px 32px;border-bottom:1px solid #30363d}
 h1{margin:0;font-size:20px}
 .verdict{display:inline-block;padding:8px 16px;border-radius:8px;font-weight:700;margin-top:12px}
 .good{background:#1a3d2b;color:#5ee08a} .warn{background:#3d340f;color:#f2cc60} .bad{background:#4d1f1f;color:#ff7b72}
 main{padding:24px 32px}
 .meta{color:#8b949e;font-size:13px}
 .tactic{margin:24px 0 8px;font-size:16px;border-bottom:1px solid #30363d;padding-bottom:4px}
 table{width:100%;border-collapse:collapse;margin-bottom:8px}
 td,th{text-align:left;padding:8px;border-bottom:1px solid #21262d;vertical-align:top;font-size:13px}
 .CRITICAL{color:#ff7b72;font-weight:700}.HIGH{color:#ffa657;font-weight:700}.MEDIUM{color:#f2cc60}.LOW{color:#8b949e}.INFO{color:#6e7681}
 code{background:#161b22;padding:2px 5px;border-radius:4px;font-size:12px;word-break:break-all}
</style></head><body>
<header>
 <h1>BreachHound — Compromise Assessment</h1>
 <div class="meta">{{.Host.Hostname}} · {{.Host.OS}} · generated {{.GeneratedAt}}</div>
 <div class="verdict {{.VerdictCSS}}">{{.Verdict}} — risk {{.RiskScore}}/100</div>
</header>
<main>
{{if not .Tactics}}<p>No findings recorded.</p>{{end}}
{{range .Tactics}}
 <div class="tactic">{{.Tactic}}</div>
 <table>
  <tr><th>Severity</th><th>Title</th><th>Technique</th><th>Confidence</th><th>Evidence</th></tr>
  {{range .Findings}}
  <tr>
   <td class="{{sev .Severity}}">{{sev .Severity}}</td>
   <td>{{.Title}}<br><span class="meta">{{.Description}}</span></td>
   <td>{{.Technique}}</td>
   <td>{{conf .Confidence}}</td>
   <td>{{range .Evidence}}<code>{{.}}</code><br>{{end}}</td>
  </tr>
  {{end}}
 </table>
{{end}}
{{if .Skipped}}
 <div class="tactic">Skipped checks</div>
 <ul>{{range .Skipped}}<li class="meta">{{.}}</li>{{end}}</ul>
{{end}}
 <p class="meta" style="margin-top:32px;border-top:1px solid #30363d;padding-top:12px">
  Generated by BreachHound — a compromise-assessment tool by TK NiRMAL.
 </p>
</main></body></html>`
